### ISSUE TITLE
go build cgo error

### ISSUE THREAD

**Issue by lzjluzijie** [majestrate/cryptonight#1]
I am trying to go get this project.
`go get github.com/majestrate/cryptonight`
But there is a cgo error.
```
go build github.com/majestrate/cryptonight: invalid flag in #cgo CFLAGS: -maes
````
os: windows10 64bit

**Comment by majestrate** [comment]
looks like go restricted some of the cgo features

the fix is to set `CGO_CFLAGS_ALLOW='-maes'` when building any projects that use this library.

also, please note that this repo is VERY out of date and does not contain the newer monero hash stuff.
